### ISSUE TITLE
New release to fix Python 3.6+ support?

### ISSUE THREAD

**Issue by akien-mga** [bpython/curtsies#121]
I noticed that my `bpython` package in Mageia 8 (Python 3 flavour) is throwing this error:
```
Traceback (most recent call last):
  File "/usr/bin/bpython", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typing' distribution was not found and is required by curtsies
```

I packaged curtsies 0.3.0 which is the last stable releases. Commit https://github.com/bpython/curtsies/commit/217b4f83e954837f8adc4c549c1f2f9f2bb272a7 done after 0.3.0 fixes the issue, but has yet to be included in a stable release.

As Python 2 is going to be phased out and Python 3.6+ is now mostly ubiquitous, a new release might be in order.

**Comment by sebastinas** [comment]
@thomasballinger Could you please prepare a new release?

**Comment by thomasballinger** [comment]
sure thing, can look at this tonight

**Comment by thomasballinger** [comment]
Curtsies 0.3.1 has been released included this fix, please let me know if there are any issues
